definitions:
  dto.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  dto.LoginResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      user: {}
    type: object
  dto.LogoutResponse:
    properties:
      message:
        example: Berhasil melakukan logout
        type: string
      status:
        example: success
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      confirmPassword:
        example: password123
        type: string
      email:
        example: example@email.com
        type: string
      firstName:
        example: Jhon
        type: string
      lastName:
        example: Doe
        type: string
      password:
        example: password123
        type: string
    type: object
  dto.Response:
    properties:
      message:
        example: Sucess
        type: string
      status:
        example: "200"
        type: string
    type: object
  model.Article:
    properties:
      content:
        type: string
      desc:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  model.User:
    properties:
      createdDate:
        type: string
      email:
        type: string
      id:
        type: integer
      isActive:
        type: boolean
      password:
        type: string
      updateDate:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Authentication for user
      parameters:
      - description: Login credentials
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/dto.LoginResponse'
      tags:
      - Users
  /api/logout:
    post:
      consumes:
      - application/json
      description: Logout for user
      produces:
      - application/json
      responses:
        "200":
          description: 200, Logout Berhasil
          schema:
            $ref: '#/definitions/dto.LogoutResponse'
      tags:
      - Users
  /api/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Body Request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
      tags:
      - Users
  /articles:
    get:
      consumes:
      - application/json
      description: Get details of all available articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
      summary: Get all articles
      tags:
      - Articles
    post:
      consumes:
      - application/json
      description: Create a new article with title, description and content
      parameters:
      - description: New Article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Article'
      summary: Create a new article
      tags:
      - Articles
  /users:
    get:
      consumes:
      - application/json
      description: Get details of all available user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Get all Users
      tags:
      - Users
swagger: "2.0"
